version: '3.8'

services:
  localstack:
    image: localstack/localstack
    container_name: localstack-main
    ports:
      - "192.168.1.100:4566:4566" # localstack port, change to your ip
      - "192.168.1.100:4571:4571" # localstack port, change to your ip
    env_file:
      - .env
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
